// Mock data for Organizations
export const MOCK_ORGANIZATIONS = [
  {
    id: "org_northlake",
    name: "Northlake Medical Group",
    phone: "(312) 555-1200",
    email: "info@northlake.org",
    ein: "12-3456789",
    enabled: true,
    address: {
      street: "1200 W Lake St",
      suite: "Suite 200",
      city: "Chicago",
      state: "IL",
      zip: "60601",
    },
    contact: {
      first: "Maya",
      last: "Singh",
      email: "maya@northlake.org",
      tel: "(312) 555-1201",
      fax: "(312) 555-1299",
    },
    walletCents: 0,
    referralCredits: 0,
  },
  {
    id: "org_evergreen",
    name: "Evergreen Imaging Center",
    phone: "(630) 555-4400",
    email: "contact@evergreenimaging.com",
    ein: "98-7654321",
    enabled: true,
    address: {
      street: "4550 Greenleaf Ave",
      suite: "",
      city: "Naperville",
      state: "IL",
      zip: "60563",
    },
    contact: {
      first: "Jon",
      last: "Hernandez",
      email: "jon@evergreenimaging.com",
      tel: "(630) 555-4401",
      fax: "(630) 555-4499",
    },
    walletCents: 0,
    referralCredits: 0,
  },
  {
    id: "org_sunrise",
    name: "Sunrise Specialty Clinic",
    phone: "(713) 555-7700",
    email: "hello@sunriseclinic.com",
    ein: "23-4567890",
    enabled: true,
    address: {
      street: "99 Bayou Blvd",
      suite: "Ste 12",
      city: "Houston",
      state: "TX",
      zip: "77002",
    },
    contact: {
      first: "Aisha",
      last: "Khan",
      email: "aisha@sunriseclinic.com",
      tel: "(713) 555-7701",
      fax: "(713) 555-7799",
    },
    walletCents: 0,
    referralCredits: 0,
  },
];

export const MOCK_BRANCHES = [
  { id: "br_northlake_main", orgId: "org_northlake", name: "Main", enabled: true },
  { id: "br_northlake_west", orgId: "org_northlake", name: "West", enabled: true },
  { id: "br_evergreen_main", orgId: "org_evergreen", name: "Main", enabled: true },
  { id: "br_sunrise_main", orgId: "org_sunrise", name: "Main", enabled: true },
];

export const MOCK_DEPARTMENTS = [
  { id: "dp_northlake_cardio", orgId: "org_northlake", branchId: "br_northlake_main", name: "Cardiology", enabled: true },
  { id: "dp_northlake_pulm", orgId: "org_northlake", branchId: "br_northlake_west", name: "Pulmonology", enabled: true },
  { id: "dp_evergreen_mri", orgId: "org_evergreen", branchId: "br_evergreen_main", name: "MRI", enabled: true },
  { id: "dp_sunrise_ortho", orgId: "org_sunrise", branchId: "br_sunrise_main", name: "Orthopedics", enabled: true },
];

export const MOCK_ORG_USERS = [
  {
    id: "u_orgadmin_nl",
    email: "orgadmin@northlake.org",
    firstName: "Org",
    lastName: "Admin",
    name: "Org Admin (Northlake)",
    phone: "",
    notes: "Northlake organization admin user.",
    role: "ORG_ADMIN",
    adminCap: true,
    orgId: "org_northlake",
    resetIntervalDays: 60,
    mfaEmail: false,
    enabled: true,
    password: "Admin123!",
    forceChangeNextLogin: false,
    passwordChangedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {
      referralDashboard: true,
      userPanel: false,
      paymentAdjustmentSettings: true,
      bannerManagement: true,
      financials: false,
      reports: true,
      auditLog: false,
      settings: false,
    },
    branchIds: [],
    deptIds: [],
  },
  {
    id: "u_staff_nl",
    email: "staff@northlake.org",
    firstName: "Staff",
    lastName: "User",
    name: "Staff (Northlake)",
    phone: "",
    notes: "",
    role: "STAFF",
    adminCap: false,
    orgId: "org_northlake",
    resetIntervalDays: 90,
    mfaEmail: false,
    enabled: true,
    password: "Admin123!",
    forceChangeNextLogin: false,
    passwordChangedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {
      referralDashboard: true,
      userPanel: false,
      paymentAdjustmentSettings: false,
      bannerManagement: false,
      financials: false,
      reports: false,
      auditLog: false,
      settings: false,
    },
    branchIds: ["br_northlake_main"],
    deptIds: ["dp_northlake_cardio"],
  },
];
