// Mock data for System Access page
export const MOCK_SYSTEM_ADMINS = [
  {
    id: "u_sysadmin",
    email: "sysadmin@rcn.local",
    firstName: "System",
    lastName: "Admin",
    name: "System Admin",
    phone: "",
    notes: "",
    role: "SYSTEM_ADMIN",
    adminCap: true,
    orgId: null,
    resetIntervalDays: 30,
    mfaEmail: true,
    enabled: true,
    password: "Admin123!",
    forceChangeNextLogin: false,
    passwordChangedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: {
      referralDashboard: true,
      userPanel: true,
      paymentAdjustmentSettings: true,
      bannerManagement: true,
      financials: true,
      reports: true,
      auditLog: true,
      settings: true,
    },
    branchIds: [],
    deptIds: [],
  },
];
